fart.exe -r -c -C -- .\*.html "reconnecting-websocket.min.js\x22></script>" "reconnecting-websocket.min.js\x22></script>\n<script src=\x22/lib/consts.js\x22></script><script src=\x22/lib/utils.js\x22></script><script src=\x22/lib/tokenTransformer.js\x22></script>"
fart.exe -r -c -C -- .\*.js "new ReconnectingWebSocket" "CreateProxiedReconnectingWebSocket"
fart.exe -r -c -C -- .\*.js "JSON.parse(event.data)" "event.data"
fart.exe -r -c -C -- .\*.js "24050" "${window.overlay.config.port}"
fart.exe -r -c -C -- .\*.js "127.0.0.1" "${window.overlay.config.host}"